update git initial-commit

diff --git a/home-bin/git-initial-commit b/home-bin/git-initial-commit
--- a/home-bin/git-initial-commit
+++ b/home-bin/git-initial-commit
@@ -2,7 +2,7 @@
 
 # vim: filetype=sh
 
-set -e   # exit if any command fails
+set -e # exit if any command fails
 
 # if we haven't already initialised, do so, saves an extra manual step
 git rev-parse --is-inside-work-tree >/dev/null 2>&1 || git init
@@ -20,28 +20,34 @@ topdir=$(git rev-parse --show-toplevel)
 
 # grab a .gitignore; assume we have curl
 # (currently only writing for ourselves)
-if [ -f $topdir/.gitignore ]; then
+if [ -f "$topdir/.gitignore" ]; then
     echo "WARN: $topdir/.gitignore already exists"
 else
     # now redirects somewhere else
-    curl -Ls -o $topdir/.gitignore https://gitignore.io/api/git,vim,node,ruby,go
-    git add $topdir/.gitignore
+    curl -Ls -o "$topdir/.gitignore" https://gitignore.io/api/git,vim,node,ruby,go,terraform
+    git add "$topdir/.gitignore"
+fi
+
+# drop in a prettier config (quote behaviour in vscode/yaml formatting)
+if [ ! -f "$topdir/.prettierrc" ]; then
+    cp "$HOME/.shellrc.d/assets/dot-prettierrc" "$topdir/.prettierrc"
+    git add "$topdir/.prettierrc"
 fi
 
 # drop in a pre-commit config
-if [ -f $topdir/.pre-commit-config.yaml ]; then
+if [ -f "$topdir/.pre-commit-config.yaml" ]; then
     echo "WARN: $topdir/.pre-commit-config.yaml already exists"
 else
     # if we have a "preferred" config, use it, otherwise fall back to whatever
     # the default is
-    if [ -f $HOME/.shellrc.d/assets/dot-pre-commit-config.yaml ]; then
+    if [ -f "$HOME/.shellrc.d/assets/dot-pre-commit-config.yaml" ]; then
         echo "INFO: copying preferred .pre-commit-config.yaml"
-        cp $HOME/.shellrc.d/assets/dot-pre-commit-config.yaml $topdir/.pre-commit-config.yaml
+        cp "$HOME/.shellrc.d/assets/dot-pre-commit-config.yaml" "$topdir/.pre-commit-config.yaml"
     else
         echo "INFO: using pre-commit sample-config output"
-        pre-commit sample-config > $topdir/.pre-commit-config.yaml
+        pre-commit sample-config >"$topdir/.pre-commit-config.yaml"
     fi
-    git add $topdir/.pre-commit-config.yaml
+    git add "$topdir/.pre-commit-config.yaml"
     # make sure we actually use it
     pre-commit install
 fi
